[package]
name = "ascii_art"
version = "0.1.0"
authors = ["Binod Shrestha <binodnme08@gmail.com>"]
edition = "2021"
#rust-version = "1.56"

[dependencies]
image = "0.23.6"
imageproc = "0.22.0"
rusttype = "0.9.2"